language: php
php:
  - 5.5
  - 5.4
  - 5.3
env:
  - DB=mysql
  - DB=pgsql
script: phpunit -v --coverage-clover=coverage.clover --configuration tests/travis/$DB.travis.xml
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS backup_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database backup_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS backup_tests;'; fi"
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --dev --prefer-source
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover